// const POKE_DATA = [
//   {
//     pokemon: [
//       {
//         name: "bulbasaur",
//         url: "https://pokeapi.co/api/v2/pokemon-species/1/",
//         id: "1",
//         type: ["grass", "poison"],
//         evolution: "1",
//         price: 3860,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "charmander",
//         url: "https://pokeapi.co/api/v2/pokemon-species/4/",
//         id: "4",
//         type: "fire",
//         evolution: "1",
//         price: 2870,

//         discountPrice: 2296,
//         new: null,
//       },
//       {
//         name: "squirtle",
//         url: "https://pokeapi.co/api/v2/pokemon-species/7/",
//         id: "7",
//         type: "water",
//         evolution: "1",
//         price: 2130,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "caterpie",
//         url: "https://pokeapi.co/api/v2/pokemon-species/10/",
//         id: "10",
//         type: "bug",
//         evolution: "1",
//         price: 2100,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "weedle",
//         url: "https://pokeapi.co/api/v2/pokemon-species/13/",
//         id: "13",
//         type: ["bug", "poison"],
//         evolution: "1",
//         price: 3740,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "pidgey",
//         url: "https://pokeapi.co/api/v2/pokemon-species/16/",
//         id: "16",
//         type: ["normal", "flying"],
//         evolution: "1",
//         price: 3880,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "rattata",
//         url: "https://pokeapi.co/api/v2/pokemon-species/19/",
//         id: "19",
//         type: "normal",
//         evolution: "1",
//         price: 2960,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "spearow",
//         url: "https://pokeapi.co/api/v2/pokemon-species/21/",
//         id: "21",
//         type: ["normal", "flying"],
//         evolution: "1",
//         price: 3680,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "ekans",
//         url: "https://pokeapi.co/api/v2/pokemon-species/23/",
//         id: "23",
//         type: "poison",
//         evolution: "1",
//         price: 2800,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "sandshrew",
//         url: "https://pokeapi.co/api/v2/pokemon-species/27/",
//         id: "27",
//         type: "ground",
//         evolution: "1",
//         price: 2020,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "nidoran-f",
//         url: "https://pokeapi.co/api/v2/pokemon-species/29/",
//         id: "29",
//         type: "poison",
//         evolution: "1",
//         price: 2250,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "nidoran-m",
//         url: "https://pokeapi.co/api/v2/pokemon-species/32/",
//         id: "32",
//         type: "poison",
//         evolution: "1",
//         price: 2620,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "vulpix",
//         url: "https://pokeapi.co/api/v2/pokemon-species/37/",
//         id: "37",
//         type: "fire",
//         evolution: "1",
//         price: 2150,

//         discountPrice: 1720,
//         new: null,
//       },
//       {
//         name: "zubat",
//         url: "https://pokeapi.co/api/v2/pokemon-species/41/",
//         id: "41",
//         type: ["poison", "flying"],
//         evolution: "1",
//         price: 3390,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "oddish",
//         url: "https://pokeapi.co/api/v2/pokemon-species/43/",
//         id: "43",
//         type: ["grass", "poison"],
//         evolution: "1",
//         price: 3150,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "paras",
//         url: "https://pokeapi.co/api/v2/pokemon-species/46/",
//         id: "46",
//         type: ["bug", "grass"],
//         evolution: "1",
//         price: 3120,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "venonat",
//         url: "https://pokeapi.co/api/v2/pokemon-species/48/",
//         id: "48",
//         type: ["bug", "poison"],
//         evolution: "1",
//         price: 3370,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "diglett",
//         url: "https://pokeapi.co/api/v2/pokemon-species/50/",
//         id: "50",
//         type: "ground",
//         evolution: "1",
//         price: 2230,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "meowth",
//         url: "https://pokeapi.co/api/v2/pokemon-species/52/",
//         id: "52",
//         type: "normal",
//         evolution: "1",
//         price: 2890,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "psyduck",
//         url: "https://pokeapi.co/api/v2/pokemon-species/54/",
//         id: "54",
//         type: "water",
//         evolution: "1",
//         price: 2150,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "mankey",
//         url: "https://pokeapi.co/api/v2/pokemon-species/56/",
//         id: "56",
//         type: "fighting",
//         evolution: "1",
//         price: 2460,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "growlithe",
//         url: "https://pokeapi.co/api/v2/pokemon-species/58/",
//         id: "58",
//         type: "fire",
//         evolution: "1",
//         price: 2720,

//         discountPrice: 2176,
//         new: null,
//       },
//       {
//         name: "poliwag",
//         url: "https://pokeapi.co/api/v2/pokemon-species/60/",
//         id: "60",
//         type: "water",
//         evolution: "1",
//         price: 2340,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "abra",
//         url: "https://pokeapi.co/api/v2/pokemon-species/63/",
//         id: "63",
//         type: "psychic",
//         evolution: "1",
//         price: 2940,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "machop",
//         url: "https://pokeapi.co/api/v2/pokemon-species/66/",
//         id: "66",
//         type: "fighting",
//         evolution: "1",
//         price: 2820,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "bellsprout",
//         url: "https://pokeapi.co/api/v2/pokemon-species/69/",
//         id: "69",
//         type: ["grass", "poison"],
//         evolution: "1",
//         price: 3810,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "tentacool",
//         url: "https://pokeapi.co/api/v2/pokemon-species/72/",
//         id: "72",
//         type: ["water", "poison"],
//         evolution: "1",
//         price: 3020,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "geodude",
//         url: "https://pokeapi.co/api/v2/pokemon-species/74/",
//         id: "74",
//         type: ["rock", "ground"],
//         evolution: "1",
//         price: 3580,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "venusaur",
//         url: "https://pokeapi.co/api/v2/pokemon-species/3/",
//         id: "3",
//         type: ["grass", "poison"],
//         evolution: "3",
//         price: 5010,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "charmeleon",
//         url: "https://pokeapi.co/api/v2/pokemon-species/5/",
//         id: "5",
//         type: "fire",
//         evolution: "2",
//         price: 4410,

//         discountPrice: 3528,
//         new: null,
//       },
//       {
//         name: "charizard",
//         url: "https://pokeapi.co/api/v2/pokemon-species/6/",
//         id: "6",
//         type: ["fire", "flying"],
//         evolution: "3",
//         price: 6240,

//         discountPrice: 4992,
//         new: null,
//       },
//       {
//         name: "wartortle",
//         url: "https://pokeapi.co/api/v2/pokemon-species/8/",
//         id: "8",
//         type: "water",
//         evolution: "2",
//         price: 3560,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "blastoise",
//         url: "https://pokeapi.co/api/v2/pokemon-species/9/",
//         id: "9",
//         type: "water",
//         evolution: "3",
//         price: 3820,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "metapod",
//         url: "https://pokeapi.co/api/v2/pokemon-species/11/",
//         id: "11",
//         type: "bug",
//         evolution: "2",
//         price: 4620,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "butterfree",
//         url: "https://pokeapi.co/api/v2/pokemon-species/12/",
//         id: "12",
//         type: ["bug", "flying"],
//         evolution: "3",
//         price: 6070,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "kakuna",
//         url: "https://pokeapi.co/api/v2/pokemon-species/14/",
//         id: "14",
//         type: ["bug", "poison"],
//         evolution: "2",
//         price: 4530,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "beedrill",
//         url: "https://pokeapi.co/api/v2/pokemon-species/15/",
//         id: "15",
//         type: ["bug", "poison"],
//         evolution: "3",
//         price: 6140,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "pidgeotto",
//         url: "https://pokeapi.co/api/v2/pokemon-species/17/",
//         id: "17",
//         type: ["normal", "flying"],
//         evolution: "2",
//         price: 5370,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "pidgeot",
//         url: "https://pokeapi.co/api/v2/pokemon-species/18/",
//         id: "18",
//         type: ["normal", "flying"],
//         evolution: "3",
//         price: 5260,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "raticate",
//         url: "https://pokeapi.co/api/v2/pokemon-species/20/",
//         id: "20",
//         type: "normal",
//         evolution: "2",
//         price: 4010,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "fearow",
//         url: "https://pokeapi.co/api/v2/pokemon-species/22/",
//         id: "22",
//         type: ["normal", "flying"],
//         evolution: "2",
//         price: 4790,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "arbok",
//         url: "https://pokeapi.co/api/v2/pokemon-species/24/",
//         id: "24",
//         type: "poison",
//         evolution: "2",
//         price: 4390,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "pikachu",
//         url: "https://pokeapi.co/api/v2/pokemon-species/25/",
//         id: "25",
//         type: "electric",
//         evolution: "1",
//         price: 2490,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "raichu",
//         url: "https://pokeapi.co/api/v2/pokemon-species/26/",
//         id: "26",
//         type: "electric",
//         evolution: "2",
//         price: 4800,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "sandslash",
//         url: "https://pokeapi.co/api/v2/pokemon-species/28/",
//         id: "28",
//         type: "ground",
//         evolution: "2",
//         price: 4220,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "nidorina",
//         url: "https://pokeapi.co/api/v2/pokemon-species/30/",
//         id: "30",
//         type: "poison",
//         evolution: "2",
//         price: 4690,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "nidoqueen",
//         url: "https://pokeapi.co/api/v2/pokemon-species/31/",
//         id: "31",
//         type: ["poison", "ground"],
//         evolution: "3",
//         price: 5430,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "nidorino",
//         url: "https://pokeapi.co/api/v2/pokemon-species/33/",
//         id: "33",
//         type: "poison",
//         evolution: "2",
//         price: 3750,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "nidoking",
//         url: "https://pokeapi.co/api/v2/pokemon-species/34/",
//         id: "34",
//         type: ["poison", "ground"],
//         evolution: "3",
//         price: 6360,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "clefairy",
//         url: "https://pokeapi.co/api/v2/pokemon-species/35/",
//         id: "35",
//         type: "fairy",
//         evolution: "1",
//         price: 2470,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "clefable",
//         url: "https://pokeapi.co/api/v2/pokemon-species/36/",
//         id: "36",
//         type: "fairy",
//         evolution: "2",
//         price: 3940,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "ninetales",
//         url: "https://pokeapi.co/api/v2/pokemon-species/38/",
//         id: "38",
//         type: "fire",
//         evolution: "2",
//         price: 4730,

//         discountPrice: 3784,
//         new: null,
//       },
//       {
//         name: "jigglypuff",
//         url: "https://pokeapi.co/api/v2/pokemon-species/39/",
//         id: "39",
//         type: ["normal", "fairy"],
//         evolution: "1",
//         price: 3140,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "wigglytuff",
//         url: "https://pokeapi.co/api/v2/pokemon-species/40/",
//         id: "40",
//         type: ["normal", "fairy"],
//         evolution: "2",
//         price: 4800,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "golbat",
//         url: "https://pokeapi.co/api/v2/pokemon-species/42/",
//         id: "42",
//         type: ["poison", "flying"],
//         evolution: "2",
//         price: 5030,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "gloom",
//         url: "https://pokeapi.co/api/v2/pokemon-species/44/",
//         id: "44",
//         type: ["grass", "poison"],
//         evolution: "2",
//         price: 4140,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "vileplume",
//         url: "https://pokeapi.co/api/v2/pokemon-species/45/",
//         id: "45",
//         type: ["grass", "poison"],
//         evolution: "3",
//         price: 5930,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "parasect",
//         url: "https://pokeapi.co/api/v2/pokemon-species/47/",
//         id: "47",
//         type: ["bug", "grass"],
//         evolution: "2",
//         price: 5480,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "venomoth",
//         url: "https://pokeapi.co/api/v2/pokemon-species/49/",
//         id: "49",
//         type: ["bug", "poison"],
//         evolution: "2",
//         price: 4700,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "dugtrio",
//         url: "https://pokeapi.co/api/v2/pokemon-species/51/",
//         id: "51",
//         type: "ground",
//         evolution: "2",
//         price: 3450,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "persian",
//         url: "https://pokeapi.co/api/v2/pokemon-species/53/",
//         id: "53",
//         type: "normal",
//         evolution: "2",
//         price: 4280,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "golduck",
//         url: "https://pokeapi.co/api/v2/pokemon-species/55/",
//         id: "55",
//         type: "water",
//         evolution: "2",
//         price: 4180,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "primeape",
//         url: "https://pokeapi.co/api/v2/pokemon-species/57/",
//         id: "57",
//         type: "fighting",
//         evolution: "2",
//         price: 4930,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "arcanine",
//         url: "https://pokeapi.co/api/v2/pokemon-species/59/",
//         id: "59",
//         type: "fire",
//         evolution: "2",
//         price: 4610,

//         discountPrice: 3688,
//         new: null,
//       },
//       {
//         name: "poliwhirl",
//         url: "https://pokeapi.co/api/v2/pokemon-species/61/",
//         id: "61",
//         type: "water",
//         evolution: "2",
//         price: 4950,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "poliwrath",
//         url: "https://pokeapi.co/api/v2/pokemon-species/62/",
//         id: "62",
//         type: ["water", "fighting"],
//         evolution: "3",
//         price: 5720,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "kadabra",
//         url: "https://pokeapi.co/api/v2/pokemon-species/64/",
//         id: "64",
//         type: "psychic",
//         evolution: "2",
//         price: 3730,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "alakazam",
//         url: "https://pokeapi.co/api/v2/pokemon-species/65/",
//         id: "65",
//         type: "psychic",
//         evolution: "3",
//         price: 5730,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "machoke",
//         url: "https://pokeapi.co/api/v2/pokemon-species/67/",
//         id: "67",
//         type: "fighting",
//         evolution: "2",
//         price: 4500,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "machamp",
//         url: "https://pokeapi.co/api/v2/pokemon-species/68/",
//         id: "68",
//         type: "fighting",
//         evolution: "3",
//         price: 5890,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "weepinbell",
//         url: "https://pokeapi.co/api/v2/pokemon-species/70/",
//         id: "70",
//         type: ["grass", "poison"],
//         evolution: "2",
//         price: 4230,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "victreebel",
//         url: "https://pokeapi.co/api/v2/pokemon-species/71/",
//         id: "71",
//         type: ["grass", "poison"],
//         evolution: "3",
//         price: 5370,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "tentacruel",
//         url: "https://pokeapi.co/api/v2/pokemon-species/73/",
//         id: "73",
//         type: ["water", "poison"],
//         evolution: "2",
//         price: 5110,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "graveler",
//         url: "https://pokeapi.co/api/v2/pokemon-species/75/",
//         id: "75",
//         type: ["rock", "ground"],
//         evolution: "2",
//         price: 5310,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "ponyta",
//         url: "https://pokeapi.co/api/v2/pokemon-species/77/",
//         id: "77",
//         type: "fire",
//         evolution: "1",
//         price: 2470,

//         discountPrice: 1976,
//         new: null,
//       },
//       {
//         name: "slowpoke",
//         url: "https://pokeapi.co/api/v2/pokemon-species/79/",
//         id: "79",
//         type: ["water", "psychic"],
//         evolution: "1",
//         price: 3230,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "magnemite",
//         url: "https://pokeapi.co/api/v2/pokemon-species/81/",
//         id: "81",
//         type: ["electric", "steel"],
//         evolution: "1",
//         price: 3970,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "farfetchd",
//         url: "https://pokeapi.co/api/v2/pokemon-species/83/",
//         id: "83",
//         type: ["normal", "flying"],
//         evolution: "1",
//         price: 3610,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "doduo",
//         url: "https://pokeapi.co/api/v2/pokemon-species/84/",
//         id: "84",
//         type: ["normal", "flying"],
//         evolution: "1",
//         price: 3510,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "seel",
//         url: "https://pokeapi.co/api/v2/pokemon-species/86/",
//         id: "86",
//         type: "water",
//         evolution: "1",
//         price: 2860,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "grimer",
//         url: "https://pokeapi.co/api/v2/pokemon-species/88/",
//         id: "88",
//         type: "poison",
//         evolution: "1",
//         price: 2820,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "shellder",
//         url: "https://pokeapi.co/api/v2/pokemon-species/90/",
//         id: "90",
//         type: "water",
//         evolution: "1",
//         price: 2790,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "gastly",
//         url: "https://pokeapi.co/api/v2/pokemon-species/92/",
//         id: "92",
//         type: ["ghost", "poison"],
//         evolution: "1",
//         price: 3830,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "onix",
//         url: "https://pokeapi.co/api/v2/pokemon-species/95/",
//         id: "95",
//         type: ["rock", "ground"],
//         evolution: "1",
//         price: 3630,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "drowzee",
//         url: "https://pokeapi.co/api/v2/pokemon-species/96/",
//         id: "96",
//         type: "psychic",
//         evolution: "1",
//         price: 2810,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "krabby",
//         url: "https://pokeapi.co/api/v2/pokemon-species/98/",
//         id: "98",
//         type: "water",
//         evolution: "1",
//         price: 2280,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "voltorb",
//         url: "https://pokeapi.co/api/v2/pokemon-species/100/",
//         id: "100",
//         type: "electric",
//         evolution: "1",
//         price: 2160,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "exeggcute",
//         url: "https://pokeapi.co/api/v2/pokemon-species/102/",
//         id: "102",
//         type: ["grass", "psychic"],
//         evolution: "1",
//         price: 3450,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "cubone",
//         url: "https://pokeapi.co/api/v2/pokemon-species/104/",
//         id: "104",
//         type: "ground",
//         evolution: "1",
//         price: 2180,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "lickitung",
//         url: "https://pokeapi.co/api/v2/pokemon-species/108/",
//         id: "108",
//         type: "normal",
//         evolution: "1",
//         price: 2820,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "koffing",
//         url: "https://pokeapi.co/api/v2/pokemon-species/109/",
//         id: "109",
//         type: "poison",
//         evolution: "1",
//         price: 2030,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "rhyhorn",
//         url: "https://pokeapi.co/api/v2/pokemon-species/111/",
//         id: "111",
//         type: ["ground", "rock"],
//         evolution: "1",
//         price: 3680,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "tangela",
//         url: "https://pokeapi.co/api/v2/pokemon-species/114/",
//         id: "114",
//         type: "grass",
//         evolution: "1",
//         price: 2580,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "kangaskhan",
//         url: "https://pokeapi.co/api/v2/pokemon-species/115/",
//         id: "115",
//         type: "normal",
//         evolution: "1",
//         price: 2800,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "horsea",
//         url: "https://pokeapi.co/api/v2/pokemon-species/116/",
//         id: "116",
//         type: "water",
//         evolution: "1",
//         price: 2180,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "goldeen",
//         url: "https://pokeapi.co/api/v2/pokemon-species/118/",
//         id: "118",
//         type: "water",
//         evolution: "1",
//         price: 2750,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "staryu",
//         url: "https://pokeapi.co/api/v2/pokemon-species/120/",
//         id: "120",
//         type: "water",
//         evolution: "1",
//         price: 2550,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "scyther",
//         url: "https://pokeapi.co/api/v2/pokemon-species/123/",
//         id: "123",
//         type: ["bug", "flying"],
//         evolution: "1",
//         price: 3950,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "pinsir",
//         url: "https://pokeapi.co/api/v2/pokemon-species/127/",
//         id: "127",
//         type: "bug",
//         evolution: "1",
//         price: 2910,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "tauros",
//         url: "https://pokeapi.co/api/v2/pokemon-species/128/",
//         id: "128",
//         type: "normal",
//         evolution: "1",
//         price: 2320,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "magikarp",
//         url: "https://pokeapi.co/api/v2/pokemon-species/129/",
//         id: "129",
//         type: "water",
//         evolution: "1",
//         price: 2570,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "lapras",
//         url: "https://pokeapi.co/api/v2/pokemon-species/131/",
//         id: "131",
//         type: ["water", "ice"],
//         evolution: "1",
//         price: 3920,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "ditto",
//         url: "https://pokeapi.co/api/v2/pokemon-species/132/",
//         id: "132",
//         type: "normal",
//         evolution: "1",
//         price: 2810,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "eevee",
//         url: "https://pokeapi.co/api/v2/pokemon-species/133/",
//         id: "133",
//         type: "normal",
//         evolution: "1",
//         price: 2520,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "porygon",
//         url: "https://pokeapi.co/api/v2/pokemon-species/137/",
//         id: "137",
//         type: "normal",
//         evolution: "1",
//         price: 2300,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "omanyte",
//         url: "https://pokeapi.co/api/v2/pokemon-species/138/",
//         id: "138",
//         type: ["rock", "water"],
//         evolution: "1",
//         price: 3560,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "kabuto",
//         url: "https://pokeapi.co/api/v2/pokemon-species/140/",
//         id: "140",
//         type: ["rock", "water"],
//         evolution: "1",
//         price: 3180,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "aerodactyl",
//         url: "https://pokeapi.co/api/v2/pokemon-species/142/",
//         id: "142",
//         type: ["rock", "flying"],
//         evolution: "1",
//         price: 3810,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "articuno",
//         url: "https://pokeapi.co/api/v2/pokemon-species/144/",
//         id: "144",
//         type: ["ice", "flying"],
//         evolution: "1",
//         price: 12000,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "zapdos",
//         url: "https://pokeapi.co/api/v2/pokemon-species/145/",
//         id: "145",
//         type: ["electric", "flying"],
//         evolution: "1",
//         price: 12000,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "moltres",
//         url: "https://pokeapi.co/api/v2/pokemon-species/146/",
//         id: "146",
//         type: ["fire", "flying"],
//         evolution: "1",
//         price: 12000,

//         discountPrice: 9600,
//         new: null,
//       },
//       {
//         name: "dratini",
//         url: "https://pokeapi.co/api/v2/pokemon-species/147/",
//         id: "147",
//         type: "dragon",
//         evolution: "1",
//         price: 2500,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "mewtwo",
//         url: "https://pokeapi.co/api/v2/pokemon-species/150/",
//         id: "150",
//         type: "psychic",
//         evolution: "1",
//         price: 12000,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "rapidash",
//         url: "https://pokeapi.co/api/v2/pokemon-species/78/",
//         id: "78",
//         type: "fire",
//         evolution: "2",
//         price: 3120,

//         discountPrice: 2496,
//         new: null,
//       },
//       {
//         name: "slowbro",
//         url: "https://pokeapi.co/api/v2/pokemon-species/80/",
//         id: "80",
//         type: ["water", "psychic"],
//         evolution: "2",
//         price: 4640,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "magneton",
//         url: "https://pokeapi.co/api/v2/pokemon-species/82/",
//         id: "82",
//         type: ["electric", "steel"],
//         evolution: "2",
//         price: 5200,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "dodrio",
//         url: "https://pokeapi.co/api/v2/pokemon-species/85/",
//         id: "85",
//         type: ["normal", "flying"],
//         evolution: "2",
//         price: 4630,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "dewgong",
//         url: "https://pokeapi.co/api/v2/pokemon-species/87/",
//         id: "87",
//         type: ["water", "ice"],
//         evolution: "2",
//         price: 5350,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "muk",
//         url: "https://pokeapi.co/api/v2/pokemon-species/89/",
//         id: "89",
//         type: "poison",
//         evolution: "2",
//         price: 3660,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "cloyster",
//         url: "https://pokeapi.co/api/v2/pokemon-species/91/",
//         id: "91",
//         type: ["water", "ice"],
//         evolution: "2",
//         price: 4550,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "haunter",
//         url: "https://pokeapi.co/api/v2/pokemon-species/93/",
//         id: "93",
//         type: ["ghost", "poison"],
//         evolution: "2",
//         price: 4390,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "gengar",
//         url: "https://pokeapi.co/api/v2/pokemon-species/94/",
//         id: "94",
//         type: ["ghost", "poison"],
//         evolution: "3",
//         price: 6020,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "hypno",
//         url: "https://pokeapi.co/api/v2/pokemon-species/97/",
//         id: "97",
//         type: "psychic",
//         evolution: "2",
//         price: 4790,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "kingler",
//         url: "https://pokeapi.co/api/v2/pokemon-species/99/",
//         id: "99",
//         type: "water",
//         evolution: "3",
//         price: 3780,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "electrode",
//         url: "https://pokeapi.co/api/v2/pokemon-species/101/",
//         id: "101",
//         type: "electric",
//         evolution: "2",
//         price: 4430,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "exeggutor",
//         url: "https://pokeapi.co/api/v2/pokemon-species/103/",
//         id: "103",
//         type: ["grass", "psychic"],
//         evolution: "2",
//         price: 4240,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "marowak",
//         url: "https://pokeapi.co/api/v2/pokemon-species/105/",
//         id: "105",
//         type: "ground",
//         evolution: "2",
//         price: 4450,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "hitmonlee",
//         url: "https://pokeapi.co/api/v2/pokemon-species/106/",
//         id: "106",
//         type: "fighting",
//         evolution: "2",
//         price: 4670,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "hitmonchan",
//         url: "https://pokeapi.co/api/v2/pokemon-species/107/",
//         id: "107",
//         type: "fighting",
//         evolution: "2",
//         price: 3970,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "weezing",
//         url: "https://pokeapi.co/api/v2/pokemon-species/110/",
//         id: "110",
//         type: "poison",
//         evolution: "2",
//         price: 3970,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "rhydon",
//         url: "https://pokeapi.co/api/v2/pokemon-species/112/",
//         id: "112",
//         type: ["ground", "rock"],
//         evolution: "2",
//         price: 5010,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "chansey",
//         url: "https://pokeapi.co/api/v2/pokemon-species/113/",
//         id: "113",
//         type: "normal",
//         evolution: "1",
//         price: 2430,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "seadra",
//         url: "https://pokeapi.co/api/v2/pokemon-species/117/",
//         id: "117",
//         type: "water",
//         evolution: "2",
//         price: 4000,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "seaking",
//         url: "https://pokeapi.co/api/v2/pokemon-species/119/",
//         id: "119",
//         type: "water",
//         evolution: "2",
//         price: 3750,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "starmie",
//         url: "https://pokeapi.co/api/v2/pokemon-species/121/",
//         id: "121",
//         type: ["water", "psychic"],
//         evolution: "2",
//         price: 4810,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "mr-mime",
//         url: "https://pokeapi.co/api/v2/pokemon-species/122/",
//         id: "122",
//         type: ["psychic", "fairy"],
//         evolution: "2",
//         price: 4420,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "jynx",
//         url: "https://pokeapi.co/api/v2/pokemon-species/124/",
//         id: "124",
//         type: ["ice", "psychic"],
//         evolution: "1",
//         price: 3270,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "electabuzz",
//         url: "https://pokeapi.co/api/v2/pokemon-species/125/",
//         id: "125",
//         type: "electric",
//         evolution: "1",
//         price: 2840,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "magmar",
//         url: "https://pokeapi.co/api/v2/pokemon-species/126/",
//         id: "126",
//         type: "fire",
//         evolution: "1",
//         price: 2450,

//         discountPrice: 1960,
//         new: null,
//       },
//       {
//         name: "gyarados",
//         url: "https://pokeapi.co/api/v2/pokemon-species/130/",
//         id: "130",
//         type: ["water", "flying"],
//         evolution: "2",
//         price: 5200,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "vaporeon",
//         url: "https://pokeapi.co/api/v2/pokemon-species/134/",
//         id: "134",
//         type: "water",
//         evolution: "2",
//         price: 4430,

//         discountPrice: null,
//         new: true,
//       },
//       {
//         name: "jolteon",
//         url: "https://pokeapi.co/api/v2/pokemon-species/135/",
//         id: "135",
//         type: "electric",
//         evolution: "2",
//         price: 4550,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "flareon",
//         url: "https://pokeapi.co/api/v2/pokemon-species/136/",
//         id: "136",
//         type: "fire",
//         evolution: "2",
//         price: 3610,

//         discountPrice: 2888,
//         new: null,
//       },
//       {
//         name: "omastar",
//         url: "https://pokeapi.co/api/v2/pokemon-species/139/",
//         id: "139",
//         type: ["rock", "water"],
//         evolution: "2",
//         price: 4170,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "kabutops",
//         url: "https://pokeapi.co/api/v2/pokemon-species/141/",
//         id: "141",
//         type: ["rock", "water"],
//         evolution: "2",
//         price: 4370,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "snorlax",
//         url: "https://pokeapi.co/api/v2/pokemon-species/143/",
//         id: "143",
//         type: "normal",
//         evolution: "2",
//         price: 4890,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "dragonair",
//         url: "https://pokeapi.co/api/v2/pokemon-species/148/",
//         id: "148",
//         type: "dragon",
//         evolution: "2",
//         price: 4120,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "dragonite",
//         url: "https://pokeapi.co/api/v2/pokemon-species/149/",
//         id: "149",
//         type: ["dragon", "flying"],
//         evolution: "3",
//         price: 5080,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "mew",
//         url: "https://pokeapi.co/api/v2/pokemon-species/151/",
//         id: "151",
//         type: "psychic",
//         evolution: "1",
//         price: 12000,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "ivysaur",
//         url: "https://pokeapi.co/api/v2/pokemon-species/2/",
//         id: "2",
//         type: ["grass", "poison"],
//         evolution: "2",
//         price: 4540,

//         discountPrice: null,
//         new: null,
//       },
//       {
//         name: "golem",
//         url: "https://pokeapi.co/api/v2/pokemon-species/76/",
//         id: "76",
//         type: ["rock", "ground"],
//         evolution: "3",
//         price: 5090,

//         discountPrice: null,
//         new: null,
//       },
//     ],
//   },
// ];

// export default POKE_DATA;
